# Change these first
owner: ptoone # Your GitHub organization or username, where this repository lives
repo: Thexyz-Network-Status # The name of this repository

sites:
  - name: DNS
    url: https://dns.thexyz.com
    icon: https://www.thexyz.com/favicon.ico
  - name: Webmail
    url: https://webmail.thexyz.com
    icon: https://www.thexyz.com/favicon.ico
  - name: Email Admin
    url: https://admin.thexyz.com
    icon: https://www.thexyz.com/favicon.ico
  - name: Client Area
    url: https://www.thexyz.com
    icon: https://www.thexyz.com/favicon.ico
  - name: Quarantine
    url: https://quarantine.thexyz.com
    icon: https://www.thexyz.com/favicon.ico
  - name: Blocklists
    url: https://bl.thexyz.com
    icon: https://www.thexyz.com/favicon.ico
  - name: Roundcube
    url: https://webmail.thexyzserver.com
    icon: https://www.thexyz.com/favicon.ico
  - name: Virtual Private Servers
    url: https://login.thexyzserver.com
    icon: https://www.thexyz.com/favicon.ico

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.thexyz.com
  # baseUrl: /your-repo-name
  logoUrl: https://www.thexyz.com/images/main-logo-text-white.png
  name: Network Status
  introTitle: "**Real-time** uptime data to monitor and status Thexyz products."
  introMessage: For detailed data visit our [Network Status Page](https://www.thexyz.com/account/serverstatus.php).
  i18n:
  footer: This project is [open source]($REPO), if you need help, check the [Wiki](https://wiki.downly.net)
  navbar:
    - title: Home
      href: https://www.thexyz.com
  theme: dark    
  favicon: https://www.thexyz.com/favicon.ico
  faviconSvg: https://www.thexyz.com/images/main-logo-text-white.png
  links:
    - rel: stylesheet
      href: https://www.thexyz.com/css/downly.css
      
i18n:
  footer: This project is [open source]($REPO), if you need help, check the [Wiki](https://wiki.downly.net)
  up: "✅ Up"
  degraded: "⚠️ Degraded"
  down: "🚨 Down"
  liveStatusHtmlComment: "<!--live status-->"
  allSystemsOperational: "All monitered services are currenly operational"
  degradedPerformance: "⚠️ Degraded performance"
  completeOutage: "🚨 Complete outage"
  
    
  metaTags:
    - name: "color-scheme"
      content: "dark light"
    - name: "robots"
      content: "noindex"
      
  commitMessages:
  commitAuthorName: "Downly Bot"
  commitAuthorEmail: "bot@downly.net"    
      
user-agent: Downly-Net    

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
